server:
  port: 8080

spring:
  application:
    name: portmate

  profiles:
    include: local

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:portmate}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create

  security:
    login-url: ${LOGIN_URL:/login}
    redirect-url: ${REDIRECT_URL:/}
    new-user-redirect-url: ${NEW_USER_REDIRECT_URL:/}
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-authentication-method: client_secret_post
            redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:8080/login/oauth2/code/kakao}
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - account_email
              - profile_image

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration-time:
    access-token: ${JWT_EXPIRATION_TIME_ACCESS_TOKEN:3600}
    refresh-token: ${JWT_EXPIRATION_TIME_REFRESH_TOKEN:7776000}
